### ISSUE TITLE
random_normal(double mean, double sd) - not working 

### ISSUE THREAD

**Issue by EstherHKim** [UPPAALModelChecker/UPPAAL-Meta#136]
**Describe the bug**
The function described in the instruction seems like same function as normal(double mean, double sd). 

double random_normal(double mean, double sd) — pseudo random number distributed according to [Normal (Gaussian) distribution](https://en.wikipedia.org/wiki/Normal_distribution) for a given mean and standard deviation sd.

https://docs.uppaal.org/language-reference/expressions/ 

**To Reproduce**
1. Go to 'editor'
2. Describe 'double random_normal(double mean, double sd)'

**Expected behavior**
The function is expected to work . It is not functional problem. 

**Version(s) of UPPAAL tested**
UPPAAL 4.1.20-stratego-10-beta12

**Screenshots**
![stratego_error_random_normal](https://user-images.githubusercontent.com/89918210/190084468-9caf0e4c-1d44-428c-99ee-cc8055e7177a.png)

![stratego_error_random_normal2](https://user-images.githubusercontent.com/89918210/190084853-306ddad5-e6fb-49b5-975c-b438144b6aaa.png)

**Desktop (please complete the following information):**
 - Version [UPPAAL 4.1.20-stratego-10-beta12]
 - OS, Java version: [Ubuntu 20.04 Java 11 ]

**Additional context**

**Comment by thorulf4** [comment]
Uppaal does not allow custom functions to be named `random_normal`, as its a reserved name. Otherwise it would be ambiguous whether we want to call the custom or built-in function. The error goes away when I rename the function.
![image](https://user-images.githubusercontent.com/10059450/190149955-de501e71-498f-469f-8519-33932fc4a676.png)
