### ISSUE TITLE
Deb package does not work when installed in Pop!_OS

### ISSUE THREAD

**Issue by atjn** [UPPAALModelChecker/UPPAAL-Meta#248]
**Describe the bug**
If you install UPPAAL in [Pop!_OS](https://pop.system76.com/) via the deb package, the application will not launch.

**To Reproduce**
The following video shows UPPAAL being installed in a completely fresh Pop!_OS installation, running in a VM.

https://github.com/UPPAALModelChecker/UPPAAL-Meta/assets/20535393/eb34929a-64f8-4133-acd5-89d3a2ed1532

**Expected behavior**
The application launches.

**Version(s) of UPPAAL tested**
5.0.0 (rev. 714BA9DB36F49691), 2023-06-21

**Screenshots**
See above video

**Desktop (please complete the following information):**
 - UPPAAL 5.0.0 (rev. 714BA9DB36F49691), 2023-06-21
 - Pop!_OS 22.04 LTS (updated with latest packages as of Feb. 7) (no Nvidia drivers)

**Additional context**
Pop!_OS:
- is a fork of Ubuntu, based on Debian.
- uses a custom version of [Gnome](https://www.gnome.org/) for the desktop, it runs in X11.
- uses [Eddy](https://github.com/pop-os/eddy/tree/master_jammy) for deb package installation.

It seems like the UPPAAL process is never started or quickly encounters a fatal error, because when I try to launch it, I cannot find the process in my resource manager.

If I download the zip package and follow [the installation instructions for Linux](https://uppaal.org/downloads/), the zip application can launch and works as expected.

**Comment by mikucionisaau** [comment]
Thank you for the report! 
The OS-specific packages are still experimental.

It seems that the issue is with `libc` version in the launcher :-(
Here is how to diagnose it:
```shell
strace /opt/uppaal/bin/uppaal-5.0.0
```
which crashes briefly after loading `/lib/x86_64-linux-gnu/libc.so.6`

A workaround is to launch Uppaal directly:
```shell
/opt/uppaal/lib/app/uppaal
```

A working desktop shortcut can be created by running `AddLinks.sh` (same as with ZIP):
```shell
/opt/uppaal/lib/app/AddLinks.sh
```
Then `Uppaal-5.0.0` icon should appear on your Desktop: right-click on it and choose `Allow Launching`, then double click to run.

Now I have re-generated the `deb` and `rpm` packages on Ubuntu-22.04 LTS, so the launching issue should be fixed if you download again, albeit I am not sure the `Pop!_OS`.

Ubuntu-22.04-LTS uses GLIBC 2.35 (check by running `/lib/x86_64-linux-gnu/libc.so.6 --version`), so it should work with anything newer and likely to crash with older.

I would appreciate any follow up comments.

**Comment by atjn** [comment]
Thank you for looking into it!
I just downloaded the new package and it works perfectly in the Pop!_OS VM.
