### ISSUE TITLE
Synchronizations in TIGA are not controlled by emitter if receiver is uncontrollable

### ISSUE THREAD

**Issue by NicEastvillage** [UPPAALModelChecker/UPPAAL-Meta#304]
**Describe the bug**
If both controllable and uncontrollable edges are part of a synchronization, the transition is considered uncontrollable, even if the `signal!` is on a controllable edge. As a result, the TIGA algorithm produce incorrects results and strategies.

The error occurs in the TIGA backward algorithm. The algorithm does not consider who initiates the synchronization, resulting the "uncontrollable" that can block other controllable transitions.

**To Reproduce**
Consider the following templates:
Emitter:
![image](https://github.com/user-attachments/assets/9af9710c-f9ca-4d9d-95d9-e620fb97f9c9)

Receiver:
![image](https://github.com/user-attachments/assets/7474757e-18d3-4209-8460-9543aa5f3c97)

The following query is unsatisfied (unexpectedly):
```
control: A<> Emitter.A
```

**Expected behavior**
A) Since the `signal!` is on a controllable edge, the environment has no say in whether the synchronization transition is taken. Hence, a strategy to reach `Emitter.A` should exist.

B) In the presence of two Receiver instances, I'd expect the controller to be in control of whether a synchronization happens (as per A), but additionally, I'd expect that the environment controls which of the two possible synchronizations occur.

**Additional Comments**
C) I am not sure if the following is a bug or not, but the behavior appears odd and is closely related. The following query is unsatisfied:
```
control: A<> Emitter.B
```
It is also unsatisfied if an invariant `x<=2` is added to location R1 in the receiver. In other words, the uncontrollable `signal?` can refuse to synchronize, even if it prevents delaying and thus creates a deadlock.

**Versions**
UPPAAL Version 5.0.0
Windows 10
Java 11

**Comment by NicEastvillage** [comment]
Please let me know if case C) is expected (with/without invariant) as I am working on a similar algorithm for timed ATL.

**Comment by NicEastvillage** [comment]
I have discussed the semantics with Didier Lime, who co-authored the original TIGA paper. He says they landed on the current synchronization semantics, where the environment is very powerful, to be conservative. However, he also thinks the expected behavior I described above make more sense. It is slightly more expressive and also extends naturally to ATL.

To be explicit, we think the semantics should be as follows:
- The player in control of `signal!` decides *if* a synchronization happens. The other player cannot prevent the synchronization from happening, even if they control all the `signal?`.
- If there is more than one possible `signal?` synchronization:
  - If the environment controls all enabled `signal?` edges, then the environment decides which one synchronizes.
  - If the controller controls all enabled `signal?` edges, then the controller decides which one synchronizes.
  - If there is a mix of control, the environment has precedence and decides which of its edges synchronizes or whether the controller must instead pick one of theirs.
  
For broadcast channel synchronization the semantics are the same, except all enabled `signals?` must synchronize.
- If there are multiple enabled `signal?` edges from the same location, only one of them can synchronize, and the environment has precedence like the last case above.

And by the way, the current synchronization-controllability semantics are currently [undocumented](https://docs.uppaal.org/language-reference/system-description/templates/edges/#synchronisations), which is one of the reasons we are trying to define the expected behavior.

One downside to this semantics is, that the strategy now must also define what to do in case of multiple possible synchronizations.

**Comment by mikucionisaau** [comment]
TIGA developers (Alexandre and Kim) made a design decision that the transition is uncontrollable if it involves an uncontrollable edge. So `control: A<> Emitter.A` is not satisfied, because the opponent can prevent transition to `Emitter.A` by going to `Emitter.B`.

The C part is independent from synchronization.
Let me elaborate on the simplified case:
![image](https://github.com/user-attachments/assets/5cafb888-ae8e-47c9-84ae-0480538fb790)
UPPAAL does not find a strategy for `control: A<> Goal`, because:
1) the strategy is a mapping from a state to a set of actions
2) at the initial state `(Init,x==0)` we have two options: either delay or go to `Alt` (`Goal` is not controllable). Transition to `Alt` is not interesting, so I focus on delay.
3) the above applies to all states reachable from initial state through delay, i.e. alll `(Init,x<2)`, but at state `(Init, x==2)` delay option is no longer available, so we have only transition to `Alt` and thus we are forced to take it. There is no way we can reach `Goal`.

Interestingly if we add a guard `x<2` on edge `Init -> Alt`, then the strategy is available!
UPPAAL also finds a strategy if the edge to `Alt` is removed.
It's counter-intuitive, but it works.

**Comment by NicEastvillage** [comment]
The example you give is completely intuitive for me. What is unintuitive for me is that the environment can completely control a synchronization transition where the "!"-edge is controllable. However, if that is the intended semantics, then there are indeed no bugs.

It has a few consequences for the verbosity of the timed multiplayer games I consider in my ATL extension. For instance. instead of making a single "?"-edge that can listen to "!"s from any player, you instead have to make a "?"-edge per player. However, it is not worth changing the semantics (and definitions of strategies) to mitigate such minor problems.
